### PR TITLE
Added package.json

### PR DESCRIPTION
**Pull request by dodozhang21**
I'd like to add a package.json so this repo can be installed as a node package via npm. Thanks

### CODE REVIEW

**Comment by allmarkedup** [comment]
Hey @dodozhang21 - I've added this now but updated the name to `@allmarkedup/purl` to utilise my npm namespace. Thanks for the PR :-)

**Comment by dodozhang21** [comment]
I don't think npm likes the `@` in the name.

npm install git+https://github.com/allmarkedup/purl.git#v2.3.1 --save
npm ERR! addLocal Could not install /var/folders/zh/px7p3g2d30l24_lk47x6h015y2vmyr/T/npm-31918-0134aaed/git-cache-d5b08f39/1771aec03be7f0ae31d83c7f2fca6149a4581821
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/yzhang2/.nvm/versions/node/v7.2.0/bin/node" "/Users/yzhang2/.nvm/versions/node/v7.2.0/bin/npm" "install" "git+https://github.com/allmarkedup/purl.git#v2.3.1" "--save"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code EISDIR
npm ERR! errno -21
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

npm ERR! Please include the following file with any support request:
npm ERR!     /Applications/MAMP/htdocs/drp_parents/docroot/sites/parents.com/themes/parents/npm-debug.log

**Comment by dodozhang21** [comment]
I'm trying to switch to use your repo with a tag. But the commit is not in your v2.3.1 tag. Will you please add it?

```
npm install git+https://github.com/allmarkedup/purl.git#v2.3.1 --save
npm ERR! addLocal Could not install /var/folders/zh/px7p3g2d30l24_lk47x6h015y2vmyr/T/npm-31918-0134aaed/git-cache-d5b08f39/1771aec03be7f0ae31d83c7f2fca6149a4581821
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/yzhang2/.nvm/versions/node/v7.2.0/bin/node" "/Users/yzhang2/.nvm/versions/node/v7.2.0/bin/npm" "install" "git+https://github.com/allmarkedup/purl.git#v2.3.1" "--save"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code EISDIR
npm ERR! errno -21
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

npm ERR! Please include the following file with any support request:
npm ERR!     /Applications/MAMP/htdocs/drp_parents/docroot/sites/parents.com/themes/parents/npm-debug.log
```

**Comment by allmarkedup** [comment]
Done :-) v2.3.2

**Pull request merged**
